### PR TITLE
Fix #302 Elements not created at Mouse Pointer

### LINKED ISSUE #302: Elements not placed where directed by mouse
So far in Milestone 1, the diagram has tools for creation of lifelines, messages, and execution specifications.  In all cases, the "aim" of the tools is off:  the elements are not created where the mouse pointer actually indicates.  The *Logical Model* operates exclusively in absolute coördinates, but there are problems/gaps in the transformation to relative coördinate spaces in the edit-parts, especially a lack of accounting for insets introduced in the layout of certain elements (e.g., lifeline headers) and shape compartments that are implicitly offset by the space required by labels.

A solution to this problem must be tested using a JUnit framework of fixtures and assertions that assist in expression clear and legible tests cases for the visual layout of the diagram.

### PR DESCRIPTION
**Pull request by cdamus**
*This pull request is based on #301, which now includes the diagram notation objects in the **Logical Model** view.  I found access to the notation details quite helpful in debugging the diagram and developing these tests.*

This pull request comprises two commits:  one that fixes up inconsistencies in translation between local coördinate spaces in the edit-parts and the absolute coördinate space of the *Logical Model*, and one for addition of JUnit tests.

With the first commit, now the placement of elements is more accurate to where the mouse pointer was clicked by the user:

- the left edge of a new lifeline header is now put exactly at the horizontal position of the mouse pointer, and moreover the feed-back rectangle tracks properly with it
- the top edge of a new execution occurrence specification is put exactly at the vertical position of the mouse pointer
- likewise for messages (currently only supporting horizontal messages, so the message is created at the vertical location of the mouse pointer at the source end initiating the message creation)

The JUnit tests comprise three distinct parts:

- a new `EditorFixture` extending the `ModelFixture` to provide test automation and assertions in the diagram editor
- an expansion of the `GEFMatchers` class for assertions on the geometry of *figures* and *edit-parts*
- a suite of tests for the graphical edit-policies responsible for the creation of new lifeline, execution, and message elements in the diagram using these fixtures and assertions

## Help Wanted

One problem that I identified in the development of the tests is that the calculation of the absolute location of execution specification and message *figures* in the diagram (in GEF terms) is off by 5 pixels in the y dimension.  There is no such error in the location of lifeline figures; only figures that are children of or attached to lifeline bodies, so it seems to be some bug in the calculation of the absolute location of the lifeline body, itself.  I have no experience in the geometry of GEF figures and even less with border items, so I would appreciate help in finding where is the root cause of this error.

Currently, the tests account for this error with a `yCorrection` API used in formulation of the assertions.  There is a `TODO` comment to track down and fix the root cause so that we can remove this work-around in the assertions.

### CODE REVIEW

**Comment by CamilleLetavernier** [comment]
Request coordinates are always given relative to the Diagram Viewer, so it requires some transformations to get a Y coordinate relative to the Body Top, in terms of Notation coordinates (Especially, it needs to take Viewport scroll & zoom into account).

I can provide an example for the LifelineBodyGraphicalNodeEditPolicy

**Comment by CamilleLetavernier** [comment]
Hi Christian,

I've added a commit (Branch 302-aim-pointer, on this repo, so it doesn't show up in the PR). It doesn't "fix" the issues, but rather is an example how to get the correct Y-offset from the Request location. It seems that more things are going wrong from there, but that's a start :)

**Comment by planger** [comment]
@cdamus I've tested it a bit and it seems that e.g. messages are created lower than the mouse pointer. Also if I try to add a message between two existing messages, it looks like the new message is added below the lower existing message? Maybe I'm doing something wrong in testing though. Thanks!

**Comment by cdamus** [comment]
@planger I think you must be doing something wrong, considering that the JUnit tests are passing.  This is what I see on my Mac:  [brief video](https://www.dropbox.com/s/cd0yw6qnjinzvnw/seqd-aim-pointer.mp4?dl=0).

**Comment by cdamus** [comment]
Thanks for the follow-up @planger.  I wonder what could have happened?!?

**Pull request merged**
