### PR TITLE
Fix #26 Fragment Padding

### LINKED ISSUE #26: [General:007]: Fragment should have a padding
When fragments are created or moved around, SHALL keep a predefined distance with the graphical element above and below and when applicable with fragments and elements on the left and right, and elements and fragment below should be pushed when needed to enforce this constraint.

Graphical elements SHALL not overlap with each other.

- [x] Create
- [ ] Move

---
### Updated 22 November 2018

Padding SHALL NOT be enforced when the moving an element while holding the `Ctrl` key (`Alt` on Winux), which disables snapping to magnets/grid/guides.

- [ ] Padding override modifier key

_The choice of `Ctrl` key on Mac platform is awkward because it must be pressed only after the mouse button, otherwise the context menu is shown per standard Mac UI behaviour.  However, this is the GEF/GMF convention, so it is maintained here._

### PR DESCRIPTION
**Pull request by cdamus**
This branch implements changes to sweep obstacles out of the way when moving elements without the semantic re-ordering keyboard modifier, including

- nudging ("bumping along") elements out of the way when moving execution specifications
- bumping elements along when moving messages
- JUnit test coverage for the above scenarios, primarily focused on nudging down
- conversion of existing tests that asserted no change in the model (on attempt to re-order elements without the keyboard modifier) as now changes do happen, but of a different nature

### CODE REVIEW

**Comment by cdamus** [comment]
There is a problem now with resizing executions upwards:  they are moved as well as resized, but not resized by as much as intended, resulting in the bottom end being pulled up.

exec-stretch-up

**Comment by cdamus** [comment]
This commit 17f1211c3287ef3541f680672cdfd7edcca5b511 fixes the problem with nudging up on stretching an execution specification, via (amongst other refinements) implementing a generalized support for nudging upwards in the `NudgeCommand`.  A particularly thorny issue in this is the nudging up of the start occurrence of an execution specification to effectively stretch it vertically without (a) pulling up its finish occurrence also and (b) pulling other occurrences with it such as attached message ends.  The net result now is a fairly reasonable, though not perfect, nudging of elements both up and down when moving things around in the diagram.

JUnit tests are updated to cover these new scenarios, mostly by adapting existing tests.

**Comment by cdamus** [comment]
Thanks again @rschnekenbu for your review.  Commit 6422fcab5e0db7d28fe81fe15e7049486afcd9a4 addresses the issues you found, adding JUnit regression tests for each each of:
- nudging can push elements up above the top of lifeline
- moving a message doesn’t nudge elements up
- stretching an execution doesn’t nudge elements down

One of the problems in the incremental construction of complex layout commands is that normal cases (esp. create messages) can produce temporary invalid layouts that are later corrected. One such case is negative connection anchor distances, placing messages above lifelines, which are then later nudged down again.  To ensure that cases of such invalid layout result in unexecutable commands, but only when not a temporary condition, this change introduces a concept of _kill switch_. This is a command that is appended to the composite after all others at the top (edit-policy) level, which when evaluated will be unexecutable unless it was previously countermanded (such as by a command that corrects an invalid layout).

**Comment by rschnekenbu** [comment]
That works fine with me with these latest modifications! Thanks for the updated patch, @cdamus!

**Pull request merged**
