### PR TITLE
Fix #76: Snap existing messages to executions

### LINKED ISSUE #76: [Execution Specification:017]: Start of the execution specification
After a fragment reorder or creation action, a start occurrence ends at the same location (within a predefined margin) of the received event of an asynch or synch message, the receive event occurence will become the start occurrence of the execution specification and the current start occurrence will be deleted.

### PR DESCRIPTION
**Pull request by cdamus**
When moving existing messages, snap them to execution specifications to replace start/finish occurrences by the appropriate message end.  Similarly, snap executions to messages when moving executions.

A new `SnapToHelper` implementation that snaps to magnets is proposed for use by execution specification edit-parts to enable snapping their top and bottom edges to magnets (especially message ends) on the lifeline.  Accordingly, message edit-parts now also publish magnets, one on each endpoint.

This includes some enhancement of the magnets framework, in particular to allow filtering of magnet queries.  This is necessary to ensure that, for example, the magnet at the top or bottom of an execution specification doesn't hold onto that edge of the figure if the user tries to tweak it just a bit up or down.

### CODE REVIEW

**Comment by cdamus** [comment]
Alright, @planger and @rschnekenbu it looks like I've fixed the test execution to take into account platform variability in the rendering of the diagram.  So, this beast is ready for review.

**Comment by planger** [comment]
Look great, thanks! I tested it and it works nearly perfect. There are only few things I found:

1. When connecting a sync message to an execution, we still show the popup asking whether to create a behavior or an action execution, even though the execution already exists. I'd favor preventing this popup altogether when the execution already exists.
2. While the execution can be moved near an existing message to set it as start or finish, moving an execution away from a message only shifts it graphically, but keeps the message's end as start or finish. The same is also true when moving the message. I think we should move them both if the message either moves the execution specification or the message.
3. The tool allows to create a reply/create/destroy message _from_ the start of the execution (that is, the message snaps to the start), but the start/create/destroy of the execution is not updated. I would say, we should prohibit doing that in the first place afaik UML this doesn't make any sense anyway :)

This is a very nice feature, thanks!

@rschnekenbu Do you want to review the code? I had only a brief look and it seems fine to me.

**Comment by cdamus** [comment]
1. Ah, yes.  I rebased onto the recent changes that introduced this pop-up, which I promptly disabled in my run-time workbench and forgot about.
2. I thought we should leave this in the scope of #370 which requires that messages connected to executions cannot be separated from them; separating the execution from the message is the same, so would naturally be handled in that context.
3. Yes, this should have been handled in the scope of the issue that first introduced snapping the creation of messages to executions.  I'll take care of it with a follow-up commit in this PR

**Comment by planger** [comment]
> 1. Ah, yes. I rebased onto the recent changes that introduced this pop-up, which I promptly disabled in my run-time workbench and forgot about. Although, actually, this was missed in the original introduction of the pop-up because we've had message snapping for quite some time stuck_out_tongue_closed_eyes

Yeah, I take the blame :black_joker: 
Do you want me to look at it?

> 2. I thought we should leave this in the scope of #370 which requires that messages connected to executions cannot be separated from them; separating the execution from the message is the same, so would naturally be handled in that context.

Ah right, I forgot about #370. Yes, let's leave this in the scope of #370 then.

> 3. Yes, this should have been handled in the scope of the issue that first introduced snapping the creation of messages to executions. I'll take care of it with a follow-up commit in this PR

Thanks a lot!

**Comment by cdamus** [comment]
@planger I've pushed two new commits to fix these issues:

- 8042754b73de492f2557ea1ceb670c809f3b05da for the unwanted execution specification creation pop-ups
- 14b9e58b9c1a326736d9538f15117241a70da691 to disallow sending messages from execution starts and receiving messages at execution finishes

The latter requires a bit of explanation.  It's a large change only because I added some APIs to the *Logical Model* and re-generated.  On re-generation, I found that a lot of tests weren't generated for earlier additions to the model, so I had some work to do to complete them.

We need to be sure always to re-generate the edit layer and tests for the logical model whenever we make changes to it.

**Comment by planger** [comment]
Awesome, thanks @cdamus! I tested it and it works great, imho! @rschnekenbu do you want to review the code or should I?

**Comment by rschnekenbu** [comment]
> Awesome, thanks @cdamus! I tested it and it works great, imho! @rschnekenbu do you want to review the code or should I?

@planger, I'll will review today. Thanks @cdamus !

**Comment by cdamus** [comment]
Thanks, @planger and @rschnekenbu for the reviews.  Does this mean that you want to merge the PR?  Note that I cannot because the target branch is protected against me.

**Pull request merged**
