### PR TITLE
Fix #408 Delete message creation

### LINKED ISSUE #408: Cannot send delete message before any other
The editor does not permit sending a delete message from a lifeline before that lifeline sends some other message, even when the receiving lifeline has no interaction fragments covering it that would follow the destruction occurrence.

For example, it should be permitted to delete _Lifeline1_ here:

screen shot 2018-11-13 at 08 17 48 2

### PR DESCRIPTION
**Pull request by cdamus**
Don’t constrain the sending end of a delete message but only the receiving end.

@planger I think this may also at least help to address the latest issue in your PR #406.

### CODE REVIEW

**Comment by planger** [comment]
One thing I found that seems unrelated to #406 and afaics also unrelated to this change is the following scenario:
image

-->

image

Do you want to address this with this PR or should I create a new issue? Thanks!

**Comment by cdamus** [comment]
> Do you want to address this with this PR or should I create a new issue? Thanks!

Yeah, that's a new issue.

**Comment by cdamus** [comment]
> > Do you want to address this with this PR or should I create a new issue? Thanks!
> 
> Yeah, that's a new issue.

**But**, as I couldn't merge the pull request anyways, I thought I would fix it.  Commit 1997af166bb4db2666fe6ad3af0ce21833a7a4f3 addresses the execution straddling problem and the original fix is rebased onto the latest from `master`.

**Comment by cdamus** [comment]
Ping! @planger.

**Pull request merged**
