### PR TITLE
#52 Re-orient Messages

### PR DESCRIPTION
**Pull request by cdamus**
This is a request for **preliminary review** of changes for the semantic reconnection of messages.  The work is still in progress, but there are a few aspects that particularly should be looked at before this develops much further:

- in commit 058705843fbe823177cd719981ec557def921e7e, the implementation of the `Ctrl` key (or `Cmd` on Mac platform) to enable semantic reordering or switching lifelines
- in the other commit a0c8b3e91a5f7b725381d9ca2710cfb39aa0a09c, two significant changes:
  - on the one hand, reworking the `AbstractSequenceGraphicalEditPolicy` to delegate the creation of commands for reconnecting the source or target end of a connection to the *Logical Model*.  This somewhat simplifies the edit-policy
  - on the other hand, adding operations to the *Logical Model* for changing lifeline coverage of occurrences and, consequently, re-orienting of connections in the notation.  This latter especially relies on a new `DependencyContext` API to track for which dependencies additional commands are created to update lifeline coverages and notation views, to ensure that no matter at which element a lifeline coverage change is initiate, all dependencies are updated once and only once (without cycling forever)

All in all, this is some fairly substantial change that I think needs early review.  And it's also a step towards restoring the separation of edit logic into the *Logical Model* and out of the edit-parts that I think is an architectural goal.  Too much edit behaviour has, IMHO, crept into the edit-policies (which is largely my fault).

### CODE REVIEW

**Comment by cdamus** [comment]
Hi, @planger, @rschnekenbu I think it's a good time now to review this PR.  It is quite full of stuff.

The only items from Issue #52 that are not yet addressed are:
- "Any related fragment or element that cannot be inserted in the new lifeline should be removed from the diagram (i.e. a gate)."  *This point isn't addressable until we actually implement something like the gate that is a message end that doesn't cover a lifeline*
- "... and the semantical order will be recalculated." *The coverage of another lifeline doesn't in any case affect the sequence ordering of fragments.  It's strictly a horizontal concern.  We also have the requirement to be able to reorder fragments, but that is orthogonal to the concern in this issue, which is lifeline coverage.*

**Comment by rschnekenbu** [comment]
Hi @cdamus,

Sure! I'll have a look today

**Comment by cdamus** [comment]
Thanks, @rschnekenbu !  Sorry about the rebase.

I'll have a look pronto at the last two items, and the pop-up label problem.  Odd, that one.

**Comment by rschnekenbu** [comment]
In this sample model, moving msg4 from Lifeline5 to Lifeline5 or Lifeline3 is OK. Moving from Lifeline5 to Lifeline 2 causes a strange behavior.
[Demo-52.zip](https://github.com/eclipsesource/papyrus-seqd/files/2482911/Demo-52.zip)

**Comment by cdamus** [comment]
Thanks again @rschnekenbu for the review.  I think I've addressed the problems that you've identified that are not feed-back or anchor related, to be deferred.

**Comment by rschnekenbu** [comment]
Hi @cdamus,
Thanks for fixing all the identified issues! I do not see any remaing issues covered by the issue #384.

**Pull request merged**
