### PR TITLE
Issue #65 Moving execution start/finish

### PR DESCRIPTION
**Pull request by cdamus**
Implement support for moving the start or finish end of an execution specification up or down on the lifeline, including four use cases for each end:

- move a message sent/received at the execution finish/start, which pulls the execution finish/start occurrence along with it
- move an execution start/finish, which pulls the message receive/sent by the execution with it
- holding the Ctrl/Cmd key, move a message sent/received at the execution finish/start, which disconnects the message from the execution and moves it to a new position
- holding the Ctrl/Cmd key, move an execution start/finish, which disconnects the message from the execution and moves the start/finish occurrence to a new position

Also, of course, the simpler use cases of execution occurrences that spontaneously start/finish an execution, without messages being involved.

### CODE REVIEW

**Comment by cdamus** [comment]
Okay, @rschnekenbu I have now disabled the centred resizing in the execution specification, reinstated the test that tripped up on that issue, and it passes.  Ready for review!

**Comment by planger** [comment]
Sorry, I accidentally invalidated the CI check by canceling the wrong build. I've retriggered it now.

**Comment by rschnekenbu** [comment]
@cdamus, thanks for this work!

I am currently running the review. Here is my test model. I am trying to move the execution starts and ends, and I am facing several glitches:
- moving the finish with CTRL of the exec1 after async1_rcv and before sync2_snd the leads to a situation where the anchors of the messages below the new position are not updated => They are detached from lifeline, where they should be anchored back to the lifeline. I have to refresh manually each message end by moving them. Then they reconnect nicely (robust diagram implementation, where the representation is fixed semi-automatically, without crashing ;-))
- Same while moving the start of the exec1 further down.
- Resizing down exec2 by dragging its top resize handle leads to a strange position of the sync message starting this execution. The anchor is replaced from "start" to some position on the left side. I think it should stay in place.

Here is my test model:
[Demo_20181108.zip](https://github.com/eclipsesource/papyrus-seqd/files/2558362/Demo_20181108.zip)

**Comment by cdamus** [comment]
> * moving the finish with CTRL of the exec1 after async1_rcv and before sync2_snd the leads to a situation where the anchors of the messages below the new position are not updated => They are detached from lifeline, where they should be anchored back to the lifeline. 

Yeah, that's pretty cool.  I can reproduce this:

screen shot 2018-11-07 at 13 01 56

> * Same while moving the start of the exec1 further down.

Strange, I can't reproduce this.

screen shot 2018-11-07 at 13 05 03

> * Resizing down exec2 by dragging its top resize handle leads to a strange position of the sync message starting this execution. The anchor is replaced from "start" to some position on the left side. I think it should stay in place.

You mean, like this?  😉 

screen shot 2018-11-07 at 13 07 09

That looks like a late regression. This isn't caught by the JUnit tests because they only test stretching executions taller (from both ends), not shorter.  I'll change that.

**Comment by cdamus** [comment]
> > * Same while moving the start of the exec1 further down.
> 
> Strange, I can't reproduce this.

Hah.  In my JUnit test, using the same model, detach-shrinking *from the top* reattaches messages to the lifeline stem as expected but *from the bottom* shows this problem.  The exact opposite!

**Comment by cdamus** [comment]
Thanks again for the review, @rschnekenbu.  The commit ae3ffc76aa8b16512c16a25c8283e6b92c77eae4 addresses the problems that you found, with JUnit tests to check for future regressions in all of those scenarios (using your demo model).

**Comment by rschnekenbu** [comment]
Hi @cdamus, that solves indeed the issues i got while testing.  Thanks for the addition of tests! That is very valuable.

But I will be boring again ;-) I still have a bit of trouble on connection anchors: 
initial
Moving exec on Lifeline2 leaves the end of the async message on the lifeline. same as growing up the exec on Lifeline3, the async message is not covering. 
after
Surprisingly, when moving again the executions in the same direction, the message ends are updated nicely. 
 2nd move

**Comment by cdamus** [comment]
Thanks for the continued testing and exciting use cases, @rschnekenbu!  I have pushed two new commits, one that merges the latest master with the nested-executions feature and another to address the issue of failing to attach message ends to an execution specification that grows to encompass them.

**Pull request merged**
