### PR TITLE
Fix issue #343 Restrict message end movement

### PR DESCRIPTION
**Pull request by cdamus**
***Note** that this pull request is based on pull request #330 for issue #73, which is not yet merged.*

Implement the requirement to not allow movement of a message end to result in the other end being moved also to maintain semantic integrity.  Thus, only the end grabbed by the user can be moved and
then only if the resulting message (the other end always staying put) would be valid.

### CODE REVIEW

**Comment by cdamus** [comment]
The connection to the lifeline probably is happening because of the rebase, which brings in message anchors on the lifeline head that were implemented in parallel for create messages.  So, I'll need to do some work to disable the move to the lifeline head.

No immediate thoughts on the other problems.  I'll look into them.

**Comment by cdamus** [comment]
I've fixed a few more of the problems found in @planger's testing (thanks).  There is still an issue in the visual feed-back during message move remaining stuck at the start or finish of an execution specification.  A naïve fix that lets execution specifications have left- or right-side anchors with negative values or values greater than the length of the execution fixes that problem, but doesn't really make sense and breaks a JUnit test for create messages.  So, I need to work on letting the `FeedbackHelper` change not just anchor identity but also the connected node figure at each end, which determines the kind of anchor.

**Comment by cdamus** [comment]
@planger I have pushed a new commit that fixes the execution-specification insertion problems (I have checked them off in your comment).  Thus only the "Easter egg" and feedback issues remain, which as discussed off-line are of lower priority and can be deferred.

**Comment by planger** [comment]
I've opened #349 and #350 for the remaining issues mentioned in https://github.com/eclipsesource/papyrus-seqd/pull/331#issuecomment-420224330.

**Pull request merged**
